apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-portal
  namespace: employee-portal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-portal

  template:
    metadata:
      labels:
        app: employee-portal

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: employee-portal
              topologyKey: kubernetes.io/hostname

      containers:
        - name: employee-portal
          image: umangkhandelwal/julyprt:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
