apiVersion: v1
kind: Service

metadata:
  name: employee-service
  namespace: employee-portal

spec:
  selector:
    app: employee-portal

  type: NodePort

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
